services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.35.7
    container_name: weaviate
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - weaviate_data:/var/lib/weaviate
    environment:
      QUERY_DEFAULTS_LIMIT: "25"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      CLUSTER_HOSTNAME: "node1"
    restart: unless-stopped

  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    container_name: auth-service
    env_file:
      - .env
    ports:
      - "8001:8001"
    restart: unless-stopped

  preprocessing-service:
    build:
      context: .
      dockerfile: services/preprocessing-service/Dockerfile
    container_name: preprocessing-service
    volumes:
      - ./shared:/shared
      - ./shared/raw_data:/shared/raw-data:ro
    env_file:
      - .env
    ports:
      - "8000:8000"
    restart: unless-stopped

  embedding-service:
    build:
      context: .
      dockerfile: services/embedding-service/Dockerfile
    container_name: embedding-service
    env_file:
      - .env
    environment:
      WEAVIATE_HTTP_URL: http://weaviate:8080
      WEAVIATE_GRPC_HOST: weaviate
    ports:
      - "8002:8002"
    depends_on:
      - weaviate
    restart: unless-stopped

  retrieval-service:
    build:
      context: .
      dockerfile: services/retrieval-service/Dockerfile
    container_name: retrieval-service
    env_file:
      - .env
    environment:
      WEAVIATE_HTTP_URL: http://weaviate:8080
      WEAVIATE_GRPC_HOST: weaviate
    ports:
      - "8003:8003"
    depends_on:
      - weaviate
    restart: unless-stopped

  generation-service:
    build:
      context: .
      dockerfile: services/generation-service/Dockerfile
    container_name: generation-service
    env_file:
      - .env
    environment:
      RETRIEVAL_BASE_URL: http://retrieval-service:8003
    ports:
      - "8004:8004"
    depends_on:
      - retrieval-service
    restart: unless-stopped

  ingestion-service:
    build:
      context: .
      dockerfile: services/ingestion-service/Dockerfile
    container_name: ingestion-service
    env_file:
      - .env
    environment:
      INGESTION_PREPROCESSING_BASE_URL: http://preprocessing-service:8000
      INGESTION_EMBEDDING_BASE_URL: http://embedding-service:8002
      INGESTION_RAW_DIR: /shared/raw_data
      INGESTION_SOURCE_ROOT_IN_PREPROCESSING: /shared/raw_data
      WEAVIATE_HTTP_URL: http://weaviate:8080
      WEAVIATE_COLLECTION: Chunk
    ports:
      - "8005:8005"
    depends_on:
      - preprocessing-service
      - embedding-service
    volumes:
      - ./shared:/shared
      - ./shared/raw_data:/shared/raw-data:ro
    restart: unless-stopped

volumes:
  weaviate_data:
